app:
  port: 8194
  debug: True
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 5
python_path: /opt/python/bin/python3
enable_network: True
enable_preload: False
log_path: "./logs"
allowed_syscalls:
proxy:
  socks5: ''
  http: ''
  https: ''
  no_proxy: ''
allowed_env_vars: []
