---
# tasks file for b08x.llmops.antigravity

- name: Display the value of antigravity_my_variable
  ansible.builtin.debug:
    msg: "The value of antigravity_my_variable is {{ antigravity_my_variable }}"

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: antigravity_state == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: antigravity_state == 'absent'

- name: Include update tasks
  ansible.builtin.include_tasks: update.yml
  when: antigravity_state == 'latest'
