---
# tasks file for b08x.llmops.antigravity

- name: Display the value of antigravity_my_variable
  ansible.builtin.debug:
    msg: "The value of antigravity_my_variable is {{ antigravity_my_variable }}"
