---
# argument spec file for b08x.llmops.vibe

argument_specs:
  main:
    short_description: Role description.
    options:
      vibe_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
